steps:
  - name: "gcr.io/cloud-builders/gcloud"
    id: install-dependencies
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        curl -LsSf https://astral.sh/uv/0.11.7/install.sh | sh
        export PATH="$$HOME/.local/bin:$$PATH"
        uv sync --locked

  - name: "gcr.io/cloud-builders/gcloud"
    id: trigger-deployment
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        export PATH="$$HOME/.local/bin:$$PATH"
        uvx google-agents-cli@1.5.0 deploy \
          --project ${_PROD_PROJECT_ID} \
          --region ${_REGION} \
          --service-account=${_APP_SERVICE_ACCOUNT_PROD} \
          --service-name demo-agent-prod \
          --update-env-vars="OTEL_RESOURCE_ATTRIBUTES=service.version=${COMMIT_SHA},LOGS_BUCKET_NAME=${_LOGS_BUCKET_NAME_PROD}"

  - name: "gcr.io/cloud-builders/gcloud"
    id: publish-prod
    entrypoint: /bin/bash
    args:
      - "-c"
      - |
        export PATH="$$HOME/.local/bin:$$PATH"
        uvx google-agents-cli@1.5.0 publish gemini-enterprise \
          --project ${_PROD_PROJECT_ID} \
          --gemini-enterprise-app-id ${_GE_APP_ID} \
          --deployment-target agent_runtime \
          --registration-type adk \
          --display-name "demo-agent (prod)"
    waitFor: ["trigger-deployment"]

substitutions:
  _PROD_PROJECT_ID: YOUR_PROD_PROJECT_ID
  _REGION: us-central1
  _GE_APP_ID: "projects/864119621453/locations/global/collections/default_collection/engines/demo-geral_1764956727049"

logsBucket: gs://${PROJECT_ID}-demo-agent-logs/build-logs
options:
  env:
    - 'UV_PYTHON=3.12'
    - 'CI=true'
  substitutionOption: ALLOW_LOOSE
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
